[package]
name = "corrmatch-py"
version.workspace = true
description = "Python bindings for corrmatch template matching library"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false
autobins = false

[lib]
name = "corrmatch"
crate-type = ["cdylib"]
path = "src/lib.rs"
doc = false

[dependencies]
corrmatch.workspace = true
pyo3.workspace = true
numpy.workspace = true
ndarray.workspace = true

[build-dependencies]
pyo3-build-config.workspace = true
